version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jo4-site
    restart: always
    ports:
      - "6010:6010"
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py
      - FLASK_CONFIG=production
    volumes:
      - db_data:/app/instance
    networks:
      - tunnel-net

networks:
  tunnel-net:
    external: true

volumes:
  db_data: