from fpdf import FPDF
from datetime import datetime, timedelta
import os

class PDF(FPDF):
    def __init__(self, company_info, branding, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.company_info = company_info
        self.branding = branding
        
        # Helper to convert hex to RGB safely
        self.brand_rgb = self._hex_to_rgb(branding['colors']['core'])
        self.text_rgb = self._hex_to_rgb(branding['colors']['text'])
        self.bg_rgb = self._hex_to_rgb(branding['colors']['background'])

    def _hex_to_rgb(self, hex_color):
        hex_color = hex_color.lstrip('#')
        return tuple(int(hex_color[i:i+2], 16) for i in (0, 2, 4))

    def header(self):
        # Background color for the whole page
        self.set_fill_color(*self.bg_rgb)
        self.rect(0, 0, self.w, self.h, 'F')

        # Logo or Company Name
        if self.branding['logo'] and os.path.exists(self.branding['logo']):
            self.image(self.branding['logo'], 10, 10, 25)
        
        self.set_text_color(*self.brand_rgb)
        self.set_font('Helvetica', 'B', 16)
        self.set_xy(40, 15)
        self.cell(0, 10, self.company_info['name'], 0, 1, 'L')
        
        # Company Contact Info (Right Aligned)
        self.set_text_color(*self.text_rgb)
        self.set_font('Helvetica', '', 8)
        self.set_xy(self.w - 70, 12)
        self.multi_cell(60, 4, f"{self.company_info['address']}\n{self.company_info['phone']}\n{self.company_info['email']}", 0, 'R')
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(*self.brand_rgb)
        self.cell(0, 10, f'Generated by {self.company_info["name"]} - Page {self.page_no()}', 0, 0, 'C')

    def draw_table(self, items, total_amt, total_time):
        self.set_font('Helvetica', 'B', 10)
        self.set_fill_color(*self.brand_rgb)
        self.set_text_color(*self.bg_rgb)
        
        # Header
        h = 10
        self.cell(85, h, " Description", 1, 0, 'L', True)
        self.cell(20, h, "Qty", 1, 0, 'C', True)
        self.cell(25, h, "Unit Price", 1, 0, 'C', True)
        self.cell(30, h, "Hours", 1, 0, 'C', True)
        self.cell(30, h, "Total", 1, 1, 'C', True)

        # Rows
        self.set_font('Helvetica', '', 9)
        self.set_text_color(*self.text_rgb)
        for item in items:
            # Updated to use Rand (R)
            self.cell(85, 8, f" {item['description']}", 1, 0, 'L')
            self.cell(20, 8, str(item['quantity']), 1, 0, 'C')
            self.cell(25, 8, f"R{item['unit_price']:.2f}", 1, 0, 'R')
            self.cell(30, 8, str(item['estimated_time']), 1, 0, 'C')
            self.cell(30, 8, f"R{item['total']:.2f}", 1, 1, 'R')

        # Totals Row
        self.ln(2)
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(*self.brand_rgb)
        self.cell(130, 10, "GRAND TOTALS:", 0, 0, 'R')
        self.set_text_color(*self.text_rgb)
        self.cell(30, 10, f"{total_time} Hrs", 0, 0, 'C')
        self.cell(30, 10, f"R{total_amt:.2f}", 0, 1, 'R') # Updated to use Rand (R)

def run_cli():
    print("="*40)
    print("   JO4 DEV - INTERACTIVE QUOTE GEN")
    print("="*40)

    # Client Info
    c_name = input("Client Name: ")
    c_email = input("Client Email: ")
    c_addr = input("Client Address: ")

    items = []
    while True:
        print(f"\n--- Item #{len(items)+1} ---")
        desc = input("Description (or 'done'): ")
        if desc.lower() == 'done': break
        
        try:
            qty = int(input("Quantity: "))
            price = float(input("Unit Price (R): ")) # Updated prompt
            time = float(input("Estimated Hours: "))
            items.append({
                'description': desc,
                'quantity': qty,
                'unit_price': price,
                'estimated_time': time,
                'total': qty * price
            })
        except ValueError:
            print("Invalid input, please use numbers for qty/price/time.")

    if not items:
        print("No items added. Exiting.")
        return

    # Constants & Branding
    COMPANY = {
        'name': "JO4 Dev", 
        'address': "20 West Riding Road, Nigel", 
        'phone': "0826102440", 
        'email': "jroetscyber@gmail.com"
    }
    
    BRANDING = {
        'logo': "apple-touch-icon.png", # Ensure this exists or leave empty
        'colors': {'core': "#00e5cc", 'background': "#0c0c0c", 'text': "#f0f0f0"}
    }

    # Calculations
    total_amt = sum(i['total'] for i in items)
    total_time = sum(i['estimated_time'] for i in items)
    quote_no = datetime.now().strftime("Q-%y%m%d-%H%M")
    
    # Generate PDF
    pdf = PDF(COMPANY, BRANDING)
    pdf.add_page()
    
    # Title Section
    pdf.set_font('Helvetica', 'B', 22)
    pdf.set_text_color(*pdf.brand_rgb)
    pdf.cell(0, 15, f"QUOTE: {quote_no}", 0, 1, 'L')
    
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(*pdf.text_rgb)
    pdf.cell(0, 5, f"Date: {datetime.now().strftime('%Y-%m-%d')}", 0, 1, 'L')
    pdf.cell(0, 5, f"Valid for: 30 Days", 0, 1, 'L')
    pdf.ln(10)

    # Client Box
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(0, 10, "BILL TO:", 0, 1, 'L')
    pdf.set_font('Helvetica', '', 10)
    pdf.multi_cell(0, 5, f"{c_name}\n{c_email}\n{c_addr}")
    pdf.ln(10)

    pdf.draw_table(items, total_amt, total_time)
    
    # Terms
    pdf.ln(10)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.set_text_color(*pdf.brand_rgb)
    pdf.cell(0, 10, "Terms & Conditions", 0, 1, 'L')
    pdf.set_font('Helvetica', '', 8)
    pdf.set_text_color(*pdf.text_rgb)
    
    # Updated terms to include the 30-day validity and price changes
    pdf.multi_cell(0, 4, "1. This quote is valid for 30 days from the date of issue. After this period, prices and timelines may be subject to change.")

    filename = f"Quote_{c_name.replace(' ', '_')}_{quote_no}.pdf"
    pdf.output(filename)
    print(f"\n✨ Success! Quote saved as: {filename}")

if __name__ == "__main__":
    run_cli()